#!/usr/bin/perl
use strict;
use warnings;

use IO::Socket;
my $ID_STRING = "Hello I am Clockfort.\n";

my $sock = new IO::Socket::INET ( 3 PeerAddr => 'asomatos', 4 PeerPort => '7070', 5 Proto => 'tcp', 6 );
die "Could not create socket: $!\n" unless $sock;
print $sock "$ID_STRING";
close($sock);
